//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeinteenFlower.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrHeader()
        {
            this.TrDetails = new HashSet<TrDetail>();
        }
    
        public int TransactionID { get; set; }
        public int MemberID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public double DiscountPercentage { get; set; }
    
        public virtual MsEmployee MsEmployee { get; set; }
        public virtual MsMember MsMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrDetail> TrDetails { get; set; }
    }
}
